import type {
  BattingStat,
  PitchingStat,
} from "@/modules/npb/domain/models/player";
import type { StatColumn } from "./player-stat-table";

export const battingColumns: StatColumn<BattingStat>[] = [
  { key: "season", label: "年度", type: "number" },
  { key: "team", label: "球団", type: "text" },
  { key: "games", label: "試合", type: "number" },
  { key: "plate_appearances", label: "打席", type: "number" },
  { key: "at_bats", label: "打数", type: "number" },
  { key: "runs", label: "得点", type: "number" },
  { key: "hits", label: "安打", type: "number" },
  { key: "doubles", label: "二塁打", type: "number" },
  { key: "triples", label: "三塁打", type: "number" },
  { key: "home_runs", label: "本塁打", type: "number" },
  { key: "total_bases", label: "塁打", type: "number" },
  { key: "rbi", label: "打点", type: "number" },
  { key: "steals", label: "盗塁", type: "number" },
  { key: "caught_stealing", label: "盗塁刺", type: "number" },
  { key: "sacrifice_hits", label: "犠打", type: "number" },
  { key: "sacrifice_flies", label: "犠飛", type: "number" },
  { key: "walks", label: "四球", type: "number" },
  { key: "hit_by_pitch", label: "死球", type: "number" },
  { key: "strikeouts", label: "三振", type: "number" },
  { key: "grounded_into_double_plays", label: "併殺打", type: "number" },
  { key: "batting_average", label: "打率", type: "rate" },
  { key: "slugging_percentage", label: "長打率", type: "rate" },
  { key: "on_base_percentage", label: "出塁率", type: "rate" },
  { key: "ops", label: "OPS", type: "rate" },
  { key: "is_qualified", label: "規定打席", type: "qualification" },
];

export const pitchingColumns: StatColumn<PitchingStat>[] = [
  { key: "season", label: "年度", type: "number" },
  { key: "team", label: "球団", type: "text" },
  { key: "games", label: "登板", type: "number" },
  { key: "wins", label: "勝利", type: "number" },
  { key: "losses", label: "敗北", type: "number" },
  { key: "saves", label: "セーブ", type: "number" },
  { key: "holds", label: "H", type: "number" },
  { key: "hold_points", label: "HP", type: "number" },
  { key: "complete_games", label: "完投", type: "number" },
  { key: "shutouts", label: "完封勝", type: "number" },
  { key: "no_walk_complete_games", label: "無四球", type: "number" },
  { key: "winning_percentage", label: "勝率", type: "rate" },
  { key: "batters_faced", label: "打者", type: "number" },
  { key: "innings", label: "投球回", type: "number", digits: 2 },
  { key: "hits_allowed", label: "被安打", type: "number" },
  { key: "home_runs_allowed", label: "被本塁打", type: "number" },
  { key: "walks_allowed", label: "与四球", type: "number" },
  { key: "hit_by_pitch", label: "与死球", type: "number" },
  { key: "strikeouts", label: "奪三振", type: "number" },
  { key: "wild_pitches", label: "暴投", type: "number" },
  { key: "balks", label: "ボーク", type: "number" },
  { key: "runs_allowed", label: "失点", type: "number" },
  { key: "earned_runs", label: "自責点", type: "number" },
  { key: "era", label: "防御率", type: "number", digits: 2 },
  { key: "whip", label: "WHIP", type: "number", digits: 2 },
  { key: "is_qualified", label: "規定投球回", type: "qualification" },
];
